FROM rovast/ubuntu-dev-base

ARG DEBIAN_FRONTEND=noninteractive

# 安装 PHP 环境
RUN apt-get install -y \
    php7.2 php7.2-fpm \
    php7.2-mysql php7.2-curl php7.2-mbstring php7.2-gd php7.2-xml php7.2-soap
